services:
  db:
    image: postgres:16
    container_name: investment_tracker_db
    environment:
      POSTGRES_DB: investment_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - investment_tracker_pgdata:/var/lib/postgresql/data

volumes:
  investment_tracker_pgdata:
